language: c
compiler:
  - gcc

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script: cd build && cmake ../ && make


